<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

use App\Http\Controllers\StockController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\BranchStockController;
use App\Http\Controllers\StockTransferController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SystemSettingController;
use App\Http\Controllers\StockRequestController;
use App\Http\Controllers\StockMovementController;
use App\Http\Controllers\WarehouseController;
use App\Http\Controllers\CategoryController;

// Authentication routes (generated by laravel/ui)
Auth::routes();

// Protected routes
Route::middleware('auth')->group(function () {
    Route::get('/home', [DashboardController::class, 'index'])->name('home');
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    
    Route::resource('stocks', StockController::class);
    Route::get('stocks/{stock}/edit-data', [StockController::class, 'editData'])->name('stocks.edit-data');
    Route::post('stocks/replenish', [StockController::class, 'replenish'])->name('stocks.replenish');
    Route::post('stocks/{stock}/dispose', [StockController::class, 'dispose'])->name('stocks.dispose');
    Route::post('/stocks/{stock}/upload-image', [StockController::class, 'uploadImage'])->name('stocks.upload-image');
    Route::post('/stocks/import', [StockController::class, 'import'])->name('stocks.import');
    Route::post('stocks/{stock}/transfer', [StockController::class, 'stockTransfer'])->name('stocks.transfer');

    Route::resource('categories', CategoryController::class);

    Route::resource('branches', BranchController::class);
    Route::get('branches/{branch}/edit-data', [BranchController::class, 'editData'])->name('branches.edit-data');
    Route::get('/inventory', [BranchController::class, 'inventory'])->name('branches.inventory');
    Route::post('/branch-stock/dispense', [BranchStockController::class, 'dispense'])->name('branch-stock.dispense');
    Route::get('/branch-stock/track', [BranchStockController::class, 'track'])->name('branch-stock.track');

    Route::resource('warehouses', WarehouseController::class);
    Route::get('warehouses/{warehouse}/edit-data', [WarehouseController::class, 'editData'])->name('warehouses.edit-data');

    Route::resource('stock-requests', StockRequestController::class)->except(['show']);
    Route::get('stock-requests/datatable', [StockRequestController::class, 'getStockRequests'])->name('stock-requests.datatable');
    Route::post('stock-requests/{id}/approve', [StockRequestController::class, 'approve'])->name('stock-requests.approve');
    Route::post('stock-requests/{id}/reject', [StockRequestController::class, 'reject'])->name('stock-requests.reject');
    Route::post('stock-requests/bulk-approve', [StockRequestController::class, 'bulkApprove'])->name('stock-requests.bulk-approve');
    Route::post('stock-requests/bulk-reject', [StockRequestController::class, 'bulkReject'])->name('stock-requests.bulk-reject');

    Route::resource('stock-movements', StockMovementController::class);

    Route::resource('stock-transfers', StockTransferController::class);
    Route::post('stock-transfers/{stockTransfer}/approve', [StockTransferController::class, 'approve'])->name('stock-transfers.approve');
    Route::post('stock-transfers/{stockTransfer}/reject', [StockTransferController::class, 'reject'])->name('stock-transfers.reject');

    //Reports
    Route::get('/reports/issued-stocks', [ReportController::class, 'issuedStocks'])->name('reports.issued-stocks');
    Route::get('/reports/branch-stock', [ReportController::class, 'branchStock'])->name('reports.branch-stock');
    Route::get('/reports/stock-details', [ReportController::class, 'stockDetails'])->name('reports.stock-details');
    Route::get('/reports/stock-track', [ReportController::class, 'stockTracking'])->name('reports.stock-track');
    Route::get('/reports/expiry-coming-stocks', [ReportController::class, 'expiryComingStocks'])->name('reports.expiry-coming-stocks');
    Route::get('/reports/current-stocks', [ReportController::class, 'currentStocks'])->name('reports.current-stocks');
    Route::get('/reports/disposed-stocks', [ReportController::class, 'disposedStocks'])->name('reports.disposed-stocks');

    //System Settings
    //Route::prefix('system-settings')->group(function () {
        Route::resource('system-settings', SystemSettingController::class);
        //Route::get('/', [SystemSettingController::class, 'index'])->name('system-settings.index');
        Route::post('system-settings', [SystemSettingController::class, 'updateData'])->name('system-settings.update-data');
        Route::post('system-settings/logo', [SystemSettingController::class, 'updateLogo'])->name('update-logo');
        Route::post('system-settings/{settings}/remove-logo', [SystemSettingController::class, 'removeLogo'])->name('remove-logo');
    //});

    Route::get('/profile', [ProfileController::class, 'show'])->name('profile.show');
    Route::post('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('/profile/photo', [ProfileController::class, 'updatePhoto'])->name('profile.update-photo');
    Route::delete('/profile/photo', [ProfileController::class, 'removePhoto'])->name('profile.remove-photo');
});

Route::middleware(['auth','can:user_manage'])->group(function () {
    Route::resource('users', UserController::class);
    Route::post('users/{user}/assign-role', [UserController::class, 'assignRole'])->name('users.assign-role');
    Route::post('users/{user}/remove-role', [UserController::class, 'removeRole'])->name('users.remove-role');

    Route::post('users/{user}/assign-branch', [UserController::class, 'assignBranch'])->name('users.assign-branch');
    Route::post('users/{user}/remove-branch', [UserController::class, 'removeBranch'])->name('user.remove-Branch');
    
    Route::post('users/{user}/add-roles', [UserController::class, 'addRoles'])->name('users.addRoles');
    Route::post('users/{user}/remove-roles', [UserController::class, 'removeRoles'])->name('users.removeRoles');

    Route::resource('roles', RoleController::class);
    Route::get('roles/{role}/edit-data', [RoleController::class, 'editData'])->name('roles.edit-data');
    Route::resource('permissions', PermissionController::class);
    Route::post('roles/{role}/add-permissions', [RoleController::class, 'addPermissions'])->name('roles.addPermissions');
    //Route::post('roles/{role}/remove-permissions', [RoleController::class, 'removePermissions'])->name('roles.removePermissions');
    Route::post('roles/{role}/remove-permission', [RoleController::class, 'removePermission'])->name('roles.remove-permission');
    //Route::delete('/roles/{role}/remove-permission/{permission}',[RoleController::class,'removePermission'])->name('role.remove.permission');
});

Route::get('/', function () {
    return redirect()->route('login');
});


//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
