<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

use App\Http\Controllers\StockController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\StockTransferController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SystemSettingController;

// Authentication routes (generated by laravel/ui)
Auth::routes();

// Protected routes
Route::middleware('auth')->group(function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);
    Route::post('users/{user}/assign-role', [UserController::class, 'assignRole'])->name('users.assign-role');
    Route::post('users/{user}/remove-role', [UserController::class, 'removeRole'])->name('users.remove-role');
    
    Route::post('users/{user}/add-roles', [UserController::class, 'addRoles'])->name('users.addRoles');
    Route::post('users/{user}/remove-roles', [UserController::class, 'removeRoles'])->name('users.removeRoles');

    Route::resource('roles', RoleController::class);
    Route::get('roles/{role}/edit-data', [RoleController::class, 'editData'])->name('roles.edit-data');
    Route::resource('permissions', PermissionController::class);
    Route::post('roles/{role}/add-permissions', [RoleController::class, 'addPermissions'])->name('roles.addPermissions');
    //Route::post('roles/{role}/remove-permissions', [RoleController::class, 'removePermissions'])->name('roles.removePermissions');
    Route::post('roles/{role}/remove-permission', [RoleController::class, 'removePermission'])->name('roles.remove-permission');
    //Route::delete('/roles/{role}/remove-permission/{permission}',[RoleController::class,'removePermission'])->name('role.remove.permission');
    
    Route::resource('stocks', StockController::class);
    Route::resource('branches', BranchController::class);
    //Route::resource('stock-requests', StockRequestController::class);
    Route::resource('stock-transfers', StockTransferController::class);
    Route::post('stock-transfers/{stockTransfer}/approve', [StockTransferController::class, 'approve'])->name('stock-transfers.approve');
    Route::post('stock-transfers/{stockTransfer}/reject', [StockTransferController::class, 'reject'])->name('stock-transfers.reject');

    //Reports
    Route::get('/reports/issued-stocks', [ReportController::class, 'issuedStocks'])->name('reports.issued-stocks');
    Route::get('/reports/branch-stock', [ReportController::class, 'branchStock'])->name('reports.branch-stock');
    Route::get('/reports/stock-details', [ReportController::class, 'stockDetails'])->name('reports.stock-details');
    Route::get('/reports/expiry-coming-stocks', [ReportController::class, 'expiryComingStocks'])->name('reports.expiry-coming-stocks');

    //System Settings
    Route::prefix('system-settings')->group(function () {
        Route::get('/edit', [SystemSettingController::class, 'edit'])->name('system-settings.edit');
        Route::post('/update', [SystemSettingController::class, 'update'])->name('system-settings.update');
    });
});


Route::get('/', function () {
    return redirect()->route('login');
});


//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
